version: "3.8"

x-platform-profile: &platform-profile
  profiles: [ "platform" ]

x-tasks-profile: &tasks-profile
  profiles: [ "tasks" ]

x-tools-profile: &tools-profile
  profiles: [ "tools" ]

x-build-defaults: &build-defaults
  context: .
  args:
    APP_ENV: "${APP_ENV:-dev}"

x-sw-defaults: &sw-defaults
  depends_on:
    - kv
    - db
    - mq
    - s3
    - mh
  environment: &sw-defaults-environment
    REDIS_SESSION_DSN: "tcp://kv:6379/1"
    REDIS_CACHE_DSN: "redis://kv:6379/2"
    REDIS_LOCK_DSN: "redis://kv:6379/3"
    REDIS_NUMBER_DSN: "redis://kv:6379/4"
    RABBITMQ_DSN: "amqp://user:password@mq:5672/%2F"
    S3_URL: "http://localhost:9000/shopware"
    S3_BUCKET: "shopware"
    S3_REGION: "local"
    S3_ENDPOINT: "http://s3:9000"
    S3_ACCESS_KEY: "user"
    S3_SECRET_KEY: "password"
    APP_URL: "http://localhost:8000"
    DATABASE_URL: "mysql://user:password@db:3306/shopware"
    MAILER_URL: "smtp://mh:1025"
    APP_SECRET: "def0000038180dd6c4c4f8dde634d596f339cfc983efba7c00ecc69d7c17212a82802f8efc96aa655fde68771b809f364d2ac9f34ee16f71aa4b40fdf13000b8edcfa281"
    INSTANCE_ID: "OZv3IMXVJkrNdXsoyBGYKRcvyaMlYCCh"
  volumes:
    - "jwtdata:/app/config/jwt"

x-cli-defaults: &cli-defaults
  image: "ghcr.io/mistyfiky/uber-shopware/cli-${APP_ENV:-dev}:latest"
  build:
    <<: *build-defaults
    target: cli

services:

  kv:
    image: "redis:7.0.0"
    volumes:
      - "kvdata:/data"

  db:
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "shopware"
    image: "mysql:8.0.29"
    volumes:
      - "dbdata:/var/lib/mysql"
      - "./dump.sql:/docker-entrypoint-initdb.d/dump.sql"

  mq:
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    image: "rabbitmq:3.10.0-management"
    ports:
      - "15672:15672"
    volumes:
      - "mqdata:/var/lib/rabbitmq"

  s3:
    environment:
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_DEFAULT_BUCKETS: "shopware:public"
    image: "bitnami/minio:2022.5.8"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "s3data:/data"

  mh:
    image: "mailhog/mailhog:v1.0.1"
    ports:
      - "8025:8025"

  sw:
    <<: *platform-profile
    <<: *sw-defaults
    image: "ghcr.io/mistyfiky/uber-shopware/sw-${APP_ENV:-dev}:latest"
    build:
      <<: *build-defaults
      target: sw

  web:
    <<: *platform-profile
    image: "ghcr.io/mistyfiky/uber-shopware/web-${APP_ENV:-dev}:latest"
    build:
      <<: *build-defaults
      target: web
    depends_on:
      - sw
    environment:
      NGINX_FASTCGI_PASS: "sw:9000"
    ports:
      - "8000:80"

  consumer:
    <<: *platform-profile
    <<: *sw-defaults
    <<: *cli-defaults
    command: "bin/console -n messenger:consume default --time-limit=60 --memory-limit=128M"
    restart: unless-stopped

  task-runner:
    <<: *platform-profile
    <<: *sw-defaults
    <<: *cli-defaults
    command: "bin/console -n scheduled-task:run --time-limit=60 --memory-limit=128M"
    restart: unless-stopped

  install:
    <<: *tasks-profile
    <<: *sw-defaults
    <<: *cli-defaults
    environment:
      <<: *sw-defaults-environment
      SHOP_NAME: "Storefront"
      SHOP_EMAIL: "admin@localhost"
      SHOP_LOCALE: "en-GB"
      SHOP_CURRENCY: "EUR"
    command: "bin/wait-for-it.sh -s -t 60 -h db -p 3306 -- bin/install.sh"

  update:
    <<: *tasks-profile
    <<: *sw-defaults
    <<: *cli-defaults
    command: "bin/wait-for-it.sh -s -t 60 -h db -p 3306 -- bin/update.sh"

  cli:
    <<: *tools-profile
    <<: *sw-defaults
    <<: *cli-defaults

volumes:
  kvdata:
  dbdata:
  mqdata:
  s3data:
  jwtdata:
