version: "3.8"

x-platform-profile: &platform-profile
  profiles: [ "platform", "tools" ]

x-tasks-profile: &tasks-profile
  profiles: [ "tasks" ]

x-tools-profile: &tools-profile
  profiles: [ "tools" ]

x-sw-defaults: &sw-defaults
  build:
    context: .
    args:
      APP_ENV: "${APP_ENV?}"
      USER_ID: "${USER_ID?}"
      GROUP_ID: "${GROUP_ID?}"
  depends_on:
    kv:
      condition: service_started
    db:
      condition: service_started
    mq:
      condition: service_started
    s3:
      condition: service_started
    mh:
      condition: service_started
  environment: &sw-defaults-environment
    REDIS_SESSION_DSN: "tcp://kv:6379/1"
    REDIS_CACHE_DSN: "redis://kv:6379/2"
    REDIS_LOCK_DSN: "redis://kv:6379/3"
    REDIS_NUMBER_DSN: "redis://kv:6379/4"
    RABBITMQ_DSN: "amqp://user:password@mq:5672/%2F"
    S3_URL: "http://localhost:9000/shopware"
    S3_BUCKET: "shopware"
    S3_REGION: "local"
    S3_ENDPOINT: "http://s3:9000"
    S3_ACCESS_KEY: "user"
    S3_SECRET_KEY: "password"
    APP_URL: "http://localhost:8000"
    DATABASE_URL: "mysql://user:password@db:3306/shopware"
    MAILER_URL: "smtp://mh:1025"
    APP_SECRET: "def0000038180dd6c4c4f8dde634d596f339cfc983efba7c00ecc69d7c17212a82802f8efc96aa655fde68771b809f364d2ac9f34ee16f71aa4b40fdf13000b8edcfa281"
    INSTANCE_ID: "OZv3IMXVJkrNdXsoyBGYKRcvyaMlYCCh"
  image: "ghcr.io/mistyfiky/shopware/${APP_ENV?}:latest"
  volumes:
    - "jwtdata:/app/config/jwt"
    - "./stage1/app/bin:/app/bin"
    - "./stage1/app/config:/app/config"
    - "./stage1/app/public/index.php:/app/public/index.php"
    - "./stage1/app/src:/app/src"
    # TODO automate
    - "./stage2/app/custom/static-plugins/FroshTools:/app/custom/static-plugins/FroshTools"
    - "./stage3/app/bin/install.sh:/app/bin/install.sh"
    - "./stage3/app/bin/update.sh:/app/bin/update.sh"
    - "./stage3/app/bin/wait-for-it.sh:/app/bin/wait-for-it.sh"
    - "./stage3/app/config/packages:/app/config/packages"
    - "./stage3/app/config/services/custom.xml:/app/config/services/custom.xml"
    - "./stage3/app/config/services.xml:/app/config/services.xml"
    - "./stage3/app/.env:/app/.env"
    - "./stage3/app/install.lock:/app/install.lock"
    - "./app/composer.json:/app/composer.json"
    - "./app/composer.lock:/app/composer.lock"
    - "./app/vendor:/app/vendor"
    - "./app/var/plugins.json:/app/var/plugins.json"
    # FIXME prod
    # TODO automate
    - "./app/custom/static-plugins/FroshTools/src/Resources/app/administration/node_modules:/app/custom/static-plugins/FroshTools/src/Resources/app/administration/node_modules"

services:

  kv:
    image: "redis:7.0.0"
    volumes:
      - "kvdata:/data"

  db:
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "shopware"
    image: "mysql:8.0.29"
    volumes:
      - "dbdata:/var/lib/mysql"
      - "./dump.sql:/docker-entrypoint-initdb.d/dump.sql"

  mq:
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    hostname: "mq"
    image: "rabbitmq:3.10.0-management"
    ports:
      - "15672:15672"
    volumes:
      - "mqdata:/var/lib/rabbitmq"

  s3:
    environment:
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_DEFAULT_BUCKETS: "shopware:public"
    image: "bitnami/minio:2022.5.8"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "s3data:/data"

  mh:
    image: "mailhog/mailhog:v1.0.1"
    ports:
      - "8025:8025"

  shopware:
    <<: *platform-profile
    <<: *sw-defaults

  web:
    <<: *platform-profile
    depends_on:
      shopware:
        condition: service_started
    environment:
      NGINX_FASTCGI_PASS: "shopware:9000"
    image: "nginx:1.21.6"
    ports:
      - "8000:80"
    volumes:
      - "./etc/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro"

  consumer:
    <<: *platform-profile
    <<: *sw-defaults
    command: "bin/console -n messenger:consume default --time-limit=60 --memory-limit=128M"
    restart: unless-stopped

  task-runner:
    <<: *platform-profile
    <<: *sw-defaults
    command: "bin/console -n scheduled-task:run --time-limit=60 --memory-limit=128M"
    restart: unless-stopped

  permissions:
    <<: *tasks-profile
    <<: *sw-defaults
    command: "chown -R ${USER_ID?}:${GROUP_ID?} config/jwt"
    user: "root:root"

  install:
    <<: *tasks-profile
    <<: *sw-defaults
    environment:
      <<: *sw-defaults-environment
      SHOP_NAME: "Storefront"
      SHOP_EMAIL: "admin@localhost"
      SHOP_LOCALE: "en-GB"
      SHOP_CURRENCY: "EUR"
      ADMIN_PASSWORD: "password"
    command: "bin/wait-for-it.sh -s -t 60 -h db -p 3306 -- bin/install.sh"

  update:
    <<: *tasks-profile
    <<: *sw-defaults
    command: "bin/wait-for-it.sh -s -t 60 -h db -p 3306 -- bin/update.sh"

  cli:
    <<: *tools-profile
    <<: *sw-defaults
    command: "bash"

  watch-administration:
    <<: *tools-profile
    <<: *sw-defaults
    command: "bin/watch-administration.sh"
    depends_on:
      web:
        condition: service_started
    environment:
      <<: *sw-defaults-environment
      APP_URL: "http://web"
      HOST: "0.0.0.0"
      PORT: "80"
# FIXME localhost?
#      SHOPWARE_ADMIN_BUILD_ONLY_EXTENSIONS: "1"
    ports:
      - "8080:80"

volumes:
  kvdata:
  dbdata:
  mqdata:
  s3data:
  jwtdata:
