version: "3.8"

x-build-defaults: &build-defaults
  args:
    APP_ENV: "prod"

x-sw-defaults: &sw-defaults
  environment:
    APP_ENV: "prod"

x-cli-defaults: &cli-defaults
  build:
    <<: *build-defaults

services:

  sw:
    <<: *sw-defaults
    build:
      <<: *build-defaults

  web:
    build:
      <<: *build-defaults

  consumer:
    <<: *sw-defaults
    <<: *cli-defaults

  task-runner:
    <<: *sw-defaults
    <<: *cli-defaults

  system-install:
    <<: *sw-defaults
    <<: *cli-defaults

  cli:
    <<: *sw-defaults
