# syntax=docker/dockerfile:1.3

ARG NODE_VERSION=16.15.0
ARG PHP_VERSION=8.1.7
ARG PHP_EXT_INSTALLER_VERSION=1.5.25
ARG COMPOSER_VERSION=2.3.7
ARG JQ_VERSION=1.6
ARG APP_ENV=dev
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG SHOPWARE_COMPOSER_TOKEN


FROM node:${NODE_VERSION}-bullseye AS node
FROM scratch AS node-root
COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin


# STAGE 0


FROM php:${PHP_VERSION}-fpm-bullseye AS php-base
ARG PHP_EXT_INSTALLER_VERSION
ADD https://github.com/mlocati/docker-php-extension-installer/releases/download/${PHP_EXT_INSTALLER_VERSION}/install-php-extensions \
    /usr/local/bin/install-php-extensions
RUN chmod +x /usr/local/bin/install-php-extensions
RUN IPE_GD_WITHOUTAVIF=1 install-php-extensions curl dom fileinfo gd iconv intl json libxml mbstring openssl pcre pdo pdo_mysql phar simplexml sodium xml zip zlib
RUN install-php-extensions amqp apcu redis


FROM php-base AS php-prod
RUN install-php-extensions opcache
RUN mv "${PHP_INI_DIR}/php.ini-production" "${PHP_INI_DIR}/php.ini"


FROM php-base AS php-dev
RUN install-php-extensions xdebug
RUN mv "${PHP_INI_DIR}/php.ini-development" "${PHP_INI_DIR}/php.ini"


FROM php-${APP_ENV} AS php
ARG COMPOSER_VERSION
RUN install-php-extensions @composer-${COMPOSER_VERSION}
ARG JQ_VERSION
ADD https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 /usr/local/bin/jq
RUN chmod +x /usr/local/bin/jq
ARG USER_ID
ARG GROUP_ID
RUN groupadd -g ${GROUP_ID} app && useradd -u ${USER_ID} -g ${GROUP_ID} -m app


FROM scratch AS stage0-root
COPY --from=php / /
COPY stage0/usr /usr
ARG USER_ID
ARG GROUP_ID
COPY --chown=${USER_ID}:${GROUP_ID} stage0/app /app


FROM scratch AS stage0
COPY --from=stage0-root / /
ENV PHP_INI_DIR=/usr/local/etc/php
ENTRYPOINT ["docker-php-entrypoint"]
WORKDIR /app
STOPSIGNAL SIGQUIT
EXPOSE 9000
CMD ["php-fpm"]
ARG USER_ID
ARG GROUP_ID
USER ${USER_ID}:${GROUP_ID}
ARG APP_ENV
ENV APP_ENV=${APP_ENV} \
    APP_DEBUG="0"


# STAGE 1


FROM stage0 AS dependencies
ARG USER_ID
ARG GROUP_ID
COPY --chown=${USER_ID}:${GROUP_ID} stage1/app/composer.json stage1/app/composer.lock /app/
COPY --chown=${USER_ID}:${GROUP_ID} stage1/app/platform/composer.json /app/platform/composer.json
COPY --chown=${USER_ID}:${GROUP_ID} \
     stage1/app/vendor-bin/cs-fixer/composer.json \
     /app/vendor-bin/cs-fixer/composer.json
COPY --chown=${USER_ID}:${GROUP_ID} \
     stage1/app/vendor-bin/psalm/composer.json \
     /app/vendor-bin/psalm/composer.json
COPY --chown=${USER_ID}:${GROUP_ID} stage1/app/custom /app/custom
ARG PHP_VERSION
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer config platform.php "$PHP_VERSION" && \
    jq 'del(.scripts)' composer.json >composer.json.tmp && mv composer.json.tmp composer.json && \
    composer require --no-install "php:${PHP_VERSION}" && \
    composer remove --no-install shopware/recovery
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer -d vendor-bin/cs-fixer config platform.php "$PHP_VERSION" && \
    composer -d vendor-bin/psalm config platform.php "$PHP_VERSION" && \
    composer require --dev --no-install \
      $(jq -r '."require-dev" | to_entries | .[] | "\(.key):\(.value)"' platform/composer.json) && \
    composer config "allow-plugins.bamarni/composer-bin-plugin" true && \
    composer config "allow-plugins.phpstan/extension-installer" true

FROM scratch AS stage1-root
ARG USER_ID
ARG GROUP_ID
COPY --chown=${USER_ID}:${GROUP_ID} stage1/app /app
COPY --from=dependencies /app/composer.json /app/composer.lock /app/
COPY --from=dependencies \
     /app/vendor-bin/cs-fixer/composer.json \
     /app/vendor-bin/cs-fixer/composer.json
COPY --from=dependencies \
     /app/vendor-bin/psalm/composer.json \
     /app/vendor-bin/psalm/composer.json


FROM stage0 AS stage1
COPY --from=stage1-root / /


# STAGE 2


FROM stage1 AS static-plugins-base
ARG USER_ID
ARG GROUP_ID
{{#static-plugins}}
COPY --chown=${USER_ID}:${GROUP_ID} \
     stage2/app/custom/static-plugins/{{name}}/composer.json \
     /app/custom/static-plugins/{{name}}/composer.json
{{/static-plugins}}


FROM static-plugins-base AS static-plugins-prod
{{#static-plugins}}
ARG USER_ID
ARG GROUP_ID
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer require --update-no-dev \
      $(jq -r '"\(.name):\(.version)"' custom/static-plugins/{{name}}/composer.json)
{{/static-plugins}}


FROM static-plugins-base AS static-plugins-dev
{{#static-plugins}}
ARG USER_ID
ARG GROUP_ID
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer require \
      $(jq -r '"\(.name):\(.version)"' custom/static-plugins/{{name}}/composer.json)
{{/static-plugins}}


FROM static-plugins-${APP_ENV} AS static-plugins


FROM static-plugins AS store-plugins-base
ARG USER_ID
ARG GROUP_ID
ARG SHOPWARE_COMPOSER_TOKEN
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer config repositories.shopware-packages '{"type": "composer", "url": "https://packages.shopware.com"}' && \
    composer config bearer.packages.shopware.com "${SHOPWARE_COMPOSER_TOKEN}"


FROM store-plugins-base AS store-plugins-prod
{{#store-plugins}}
ARG USER_ID
ARG GROUP_ID
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer require --update-no-dev {{package}}:{{version}}
{{/store-plugins}}


FROM store-plugins-base AS store-plugins-dev
{{#store-plugins}}
ARG USER_ID
ARG GROUP_ID
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer require {{package}}:{{version}}
{{/store-plugins}}


FROM store-plugins-${APP_ENV} AS store-plugins


FROM store-plugins AS vendor-base


FROM vendor-base AS vendor-prod
ARG USER_ID
ARG GROUP_ID
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer install --no-interaction --optimize-autoloader --no-dev


FROM vendor-base AS vendor-dev
ARG USER_ID
ARG GROUP_ID
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer install --no-interaction --optimize-autoloader && \
    composer bin all install
{{#static-plugins}}


FROM vendor-base AS vendor-{{name}}
ARG USER_ID
ARG GROUP_ID
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer -d custom/static-plugins/{{name}} dump-autoload --dev && \
    touch custom/static-plugins/{{name}}/vendor/composer/InstalledVersions.php
{{/static-plugins}}


FROM vendor-${APP_ENV} AS vendor


FROM vendor AS bundle-dump
ARG USER_ID
ARG GROUP_ID
{{#static-plugins}}
COPY --chown=${USER_ID}:${GROUP_ID} stage2/app/custom/static-plugins/{{name}} /app/custom/static-plugins/{{name}}
{{/static-plugins}}
RUN bin/ci bundle:dump


FROM vendor AS node_modules-base
COPY --from=node-root / /
ENV PUPPETEER_SKIP_DOWNLOAD=1


FROM node_modules-base AS node_modules-administration
RUN --mount=type=cache,target=/home/app/.npm,uid=${USER_ID},gid=${GROUP_ID} \
    npm --prefix vendor/shopware/administration/Resources/app/administration clean-install
{{#static-plugins}}


FROM node_modules-base AS node_modules-{{name}}
RUN mkdir -p custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules
ARG USER_ID
ARG GROUP_ID
COPY --chown=${USER_ID}:${GROUP_ID} \
     stage2/app/custom/static-plugins/{{name}}/src/Resources/app/administration/package.json* \
     stage2/app/custom/static-plugins/{{name}}/src/Resources/app/administration/package-lock.json* \
     /app/custom/static-plugins/{{name}}/src/Resources/app/administration/
RUN --mount=type=cache,target=/home/app/.npm,uid=${USER_ID},gid=${GROUP_ID} \
    if [ -f custom/static-plugins/{{name}}/src/Resources/app/administration/package-lock.json ]; then \
      npm --prefix custom/static-plugins/{{name}}/src/Resources/app/administration clean-install; \
    elif [ -f custom/static-plugins/{{name}}/src/Resources/app/administration/package.json ]; then \
      npm --prefix custom/static-plugins/{{name}}/src/Resources/app/administration install; \
    else \
      mkdir -p custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules; \
    fi
{{/static-plugins}}
{{#store-plugins}}


FROM node_modules-base AS node_modules-{{name}}
RUN --mount=type=cache,target=/home/app/.npm,uid=${USER_ID},gid=${GROUP_ID} \
    if [ -f vendor/{{package}}/src/Resources/app/administration/package-lock.json ]; then \
      npm --prefix vendor/{{package}}/src/Resources/app/administration clean-install; \
    elif [ -f vendor/{{package}}/src/Resources/app/administration/package.json ]; then \
      npm --prefix vendor/{{package}}/src/Resources/app/administration install; \
    else \
      mkdir -p vendor/{{package}}/src/Resources/app/administration/node_modules; \
    fi
{{/store-plugins}}


FROM node_modules-base AS assets
COPY --from=node_modules-administration \
     /app/vendor/shopware/administration/Resources/app/administration/node_modules \
     /app/vendor/shopware/administration/Resources/app/administration/node_modules
ARG USER_ID
ARG GROUP_ID
{{#static-plugins}}
COPY --chown=${USER_ID}:${GROUP_ID} \
     stage2/app/custom/static-plugins/{{name}}/src/Resources/app/administration \
     /app/custom/static-plugins/{{name}}/src/Resources/app/administration
COPY --from=node_modules-{{name}} \
     /app/custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules \
     /app/custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules
RUN mkdir -p custom/static-plugins/{{name}}/src/Resources/public
{{/static-plugins}}
COPY --from=bundle-dump /app/var/plugins.json /app/var/plugins.json
{{#store-plugins}}
RUN jq 'del(.{{name}})' var/plugins.json >var/plugins.json.tmp && mv var/plugins.json.tmp var/plugins.json
{{/store-plugins}}
ENV PROJECT_ROOT=/app \
    SHOPWARE_ADMIN_BUILD_ONLY_EXTENSIONS=1
RUN --mount=type=cache,target=/home/app/.npm,uid=${USER_ID},gid=${GROUP_ID} \
    npm --prefix vendor/shopware/administration/Resources/app/administration run build


# FIXME separate composer file for prod and dev
FROM node_modules-base as node_modules-prod
{{#static-plugins}}
RUN mkdir -p custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules
{{/static-plugins}}


FROM stage1-root AS stage2-root
COPY --from=store-plugins /app/composer.json /app/composer.lock /app/
COPY --from=vendor /app/vendor /app/vendor
COPY --from=bundle-dump /app/var/plugins.json /app/var/plugins.json
ARG USER_ID
ARG GROUP_ID
{{#static-plugins}}
COPY --chown=${USER_ID}:${GROUP_ID} stage2/app/custom/static-plugins/{{name}} /app/custom/static-plugins/{{name}}
COPY --from=assets \
     /app/custom/static-plugins/{{name}}/src/Resources/public \
     /app/custom/static-plugins/{{name}}/src/Resources/public
COPY --from=node_modules-prod \
     /app/custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules \
     /app/custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules
{{/static-plugins}}


FROM stage1 AS stage2
COPY --from=stage2-root / /


# STAGE 3


FROM stage2-root AS stage3-root
COPY stage3/usr /usr
ARG APP_ENV
COPY stage3/usr-${APP_ENV} /usr
ARG USER_ID
ARG GROUP_ID
COPY --chown=${USER_ID}:${GROUP_ID} stage3/app /app


FROM stage2 AS stage3
COPY --from=stage3-root / /


# STAGE X


FROM stage0 AS base
COPY --from=stage3-root / /
ENV DISABLE_EXTENSIONS="1" \
    BLUE_GREEN_DEPLOYMENT="0" \
    SHOPWARE_ES_HOSTS="" \
    SHOPWARE_ES_ENABLED="0" \
    SHOPWARE_ES_INDEXING_ENABLED="0" \
    SHOPWARE_ES_INDEX_PREFIX="" \
    SHOPWARE_HTTP_CACHE_ENABLED="1" \
    SHOPWARE_HTTP_DEFAULT_TTL="7200" \
    SHOPWARE_CDN_STRATEGY_DEFAULT="id"


FROM base AS prod


FROM base AS dev
COPY --from=node-root / /
ARG USER_ID
ARG GROUP_ID
COPY --from=vendor --chown=${USER_ID}:${GROUP_ID} /app/vendor-bin/cs-fixer/vendor /app/vendor-bin/cs-fixer/vendor
COPY --from=vendor --chown=${USER_ID}:${GROUP_ID} /app/vendor-bin/psalm/vendor /app/vendor-bin/psalm/vendor
COPY --from=node_modules-administration --chown=${USER_ID}:${GROUP_ID} \
     /app/vendor/shopware/administration/Resources/app/administration/node_modules \
     /app/vendor/shopware/administration/Resources/app/administration/node_modules
{{#static-plugins}}
COPY --from=vendor-{{name}} --chown=${USER_ID}:${GROUP_ID} \
     /app/custom/static-plugins/{{name}}/vendor \
     /app/custom/static-plugins/{{name}}/vendor
COPY --from=node_modules-{{name}} --chown=${USER_ID}:${GROUP_ID} \
     /app/custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules \
     /app/custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules
{{/static-plugins}}
{{#store-plugins}}
COPY --from=node_modules-{{name}} --chown=${USER_ID}:${GROUP_ID} \
     /app/vendor/{{package}}/src/Resources/app/administration/node_modules \
     /app/vendor/{{package}}/src/Resources/app/administration/node_modules
{{/store-plugins}}


FROM ${APP_ENV}
