# syntax=docker/dockerfile:1.3

ARG NODE_VERSION=16.15.0
ARG PHP_VERSION=8.1.7
ARG PHP_EXT_INSTALLER_VERSION=1.5.25
ARG COMPOSER_VERSION=2.3.7
ARG JQ_VERSION=1.6
ARG APP_ENV=dev
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG SHOPWARE_COMPOSER_TOKEN


FROM node:${NODE_VERSION}-bullseye AS node
FROM scratch AS node-root
COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin


# STAGE 0


FROM php:${PHP_VERSION}-fpm-bullseye AS php-base
ARG PHP_EXT_INSTALLER_VERSION
ADD https://github.com/mlocati/docker-php-extension-installer/releases/download/${PHP_EXT_INSTALLER_VERSION}/install-php-extensions \
    /usr/local/bin/install-php-extensions
RUN chmod +x /usr/local/bin/install-php-extensions
RUN IPE_GD_WITHOUTAVIF=1 install-php-extensions curl dom fileinfo gd iconv intl json libxml mbstring openssl pcre pdo pdo_mysql phar simplexml sodium xml zip zlib
RUN install-php-extensions amqp apcu redis


FROM php-base AS php-prod
RUN install-php-extensions opcache
RUN mv "${PHP_INI_DIR}/php.ini-production" "${PHP_INI_DIR}/php.ini"


FROM php-base AS php-dev
RUN install-php-extensions xdebug
RUN mv "${PHP_INI_DIR}/php.ini-development" "${PHP_INI_DIR}/php.ini"


FROM php-${APP_ENV} AS php
ARG COMPOSER_VERSION
RUN install-php-extensions @composer-${COMPOSER_VERSION}
ARG JQ_VERSION
ADD https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 /usr/local/bin/jq
RUN chmod +x /usr/local/bin/jq
ARG USER_ID
ARG GROUP_ID
RUN groupadd -g ${GROUP_ID} app && useradd -u ${USER_ID} -g ${GROUP_ID} -m app


FROM scratch AS stage0-root
COPY --from=php / /
COPY stage0/usr /usr
ARG USER_ID
ARG GROUP_ID
COPY --chown=${USER_ID}:${GROUP_ID} stage0/app /app


FROM scratch AS base
COPY --from=stage0-root / /
ENV PHP_INI_DIR="/usr/local/etc/php"
ENTRYPOINT ["docker-php-entrypoint"]
WORKDIR /app
STOPSIGNAL SIGQUIT
EXPOSE 9000
CMD ["php-fpm"]
ARG USER_ID
ARG GROUP_ID
USER ${USER_ID}:${GROUP_ID}
ARG APP_ENV
ENV APP_ENV="${APP_ENV}" \
    APP_DEBUG="0" \
    PROJECT_ROOT="/app"


# STAGE 1


FROM scratch AS stage1-root
ARG USER_ID
ARG GROUP_ID
COPY --chown=${USER_ID}:${GROUP_ID} stage1/app /app


FROM base AS skeleton
COPY --from=stage1-root / /


# STAGE 2


FROM skeleton AS dependencies
RUN jq 'del(.config.platform,.config."sort-packages",.scripts)' composer.json >composer.json.tmp && mv composer.json.tmp composer.json
RUN for p in vendor-bin/*; do \
      jq 'del(.config.platform)' ${p}/composer.json >${p}/composer.json.tmp && mv ${p}/composer.json.tmp ${p}/composer.json; \
    done
ARG USER_ID
ARG GROUP_ID
ARG PHP_VERSION
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer -n require --no-install "php:${PHP_VERSION}" && \
    composer -n remove --no-install shopware/recovery && \
    composer -n require --dev --no-install $(jq -r '."require-dev" | to_entries | .[] | "\(.key):\(.value)"' platform/composer.json) && \
    composer -n config "allow-plugins.bamarni/composer-bin-plugin" true && \
    composer -n config "allow-plugins.phpstan/extension-installer" true && \
    composer -n install $([ 'prod' = "$APP_ENV" ] && echo '--no-dev') && \
    [ 'prod' = "$APP_ENV" ] || composer -n bin all install


FROM dependencies AS node_modules-administration
COPY --from=node-root / /
ARG USER_ID
ARG GROUP_ID
ENV PUPPETEER_SKIP_DOWNLOAD="1"
RUN --mount=type=cache,target=/home/app/.npm,uid=${USER_ID},gid=${GROUP_ID} \
    npm --prefix vendor/shopware/administration/Resources/app/administration clean-install

{{#static-plugins}}

FROM skeleton AS composer-{{slug}}
ARG USER_ID
ARG GROUP_ID
COPY --chown=${USER_ID}:${GROUP_ID} \
     stage2/app/custom/static-plugins/{{name}}/composer.json \
     stage2/app/custom/static-plugins/{{name}}/composer.lock \
     /app/custom/static-plugins/{{name}}/


FROM node_modules-administration AS node_modules-{{slug}}
RUN mkdir -p custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules && \
    if [ -f custom/static-plugins/{{name}}/src/Resources/app/administration/package-lock.json ]; then \
      npm --prefix custom/static-plugins/{{name}}/src/Resources/app/administration clean-install; \
    elif [ -f custom/static-plugins/{{name}}/src/Resources/app/administration/package.json ]; then \
      npm --prefix custom/static-plugins/{{name}}/src/Resources/app/administration install; \
    fi


FROM composer-{{slug}} AS vendor-{{slug}}
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer -n -d custom/static-plugins/{{name}} install $([ 'prod' = "$APP_ENV" ] && echo '--no-dev')


FROM node_modules-{{slug}} AS assets-{{slug}}
COPY --from=composer-{{slug}} /app/custom/static-plugins/{{name}} /app/custom/static-plugins/{{name}}
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer -n require $([ 'prod' = "$APP_ENV" ] && echo '--update-no-dev') $(jq -r '"\(.name):\(.version)"' custom/static-plugins/{{name}}/composer.json)
COPY --chown=${USER_ID}:${GROUP_ID} stage2/app/custom/static-plugins/{{name}} /app/custom/static-plugins/{{name}}
RUN bin/ci bundle:dump
ENV SHOPWARE_ADMIN_BUILD_ONLY_EXTENSIONS="1"
RUN --mount=type=cache,target=/home/app/.npm,uid=${USER_ID},gid=${GROUP_ID} \
    mkdir -p custom/static-plugins/{{name}}/src/Resources/public/administration && \
    if [ -n "$(jq -r 'select(.{{name}}.administration.entryFilePath != null)' var/plugins.json)" ]; then \
      npm --prefix vendor/shopware/administration/Resources/app/administration run build; \
    fi

{{/static-plugins}}

FROM dependencies AS plugins
ARG USER_ID
ARG GROUP_ID
ARG SHOPWARE_COMPOSER_TOKEN
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    if [ -n "${SHOPWARE_COMPOSER_TOKEN}" ]; then \
      composer -n config repositories.shopware-packages '{"type": "composer", "url": "https://packages.shopware.com"}'; \
      composer -n config bearer.packages.shopware.com "${SHOPWARE_COMPOSER_TOKEN}"; \
    fi
{{#static-plugins}}
COPY --chown=${USER_ID}:${GROUP_ID} stage2/app/custom/static-plugins/{{name}} /app/custom/static-plugins/{{name}}
RUN mkdir -p custom/static-plugins/{{name}}/src/Resources/public/administration
COPY --from=assets-{{slug}} \
     /app/custom/static-plugins/{{name}}/src/Resources/public/administration \
     /app/custom/static-plugins/{{name}}/src/Resources/public/administration
{{/static-plugins}}
RUN --mount=type=cache,target=/home/app/.composer,uid=${USER_ID},gid=${GROUP_ID} \
    composer -n require $([ 'prod' = "$APP_ENV" ] && echo '--update-no-dev') \
{{#static-plugins}}
      $(jq -r '"\(.name):\(.version)"' custom/static-plugins/{{name}}/composer.json) \
{{/static-plugins}}
{{#composer-plugins}}
      {{package}}:{{version}} \
{{/composer-plugins}}
      && :
RUN bin/ci bundle:dump
RUN touch var/cache/opcache-preload.php install.lock

{{#composer-plugins}}

FROM plugins AS node_modules-{{slug}}
COPY --from=node-root / /
ARG USER_ID
ARG GROUP_ID
RUN --mount=type=cache,target=/home/app/.npm,uid=${USER_ID},gid=${GROUP_ID} \
    mkdir -p vendor/{{package}}/src/Resources/app/administration/node_modules && \
    if [ -f vendor/{{package}}/src/Resources/app/administration/package-lock.json ]; then \
      npm --prefix vendor/{{package}}/src/Resources/app/administration clean-install; \
    elif [ -f vendor/{{package}}/src/Resources/app/administration/package.json ]; then \
      npm --prefix vendor/{{package}}/src/Resources/app/administration install; \
    fi

{{/composer-plugins}}

FROM stage1-root AS stage2-root
COPY --from=plugins /app/composer.json /app/composer.lock /app/
COPY --from=plugins /app/custom/static-plugins /app/custom/static-plugins
COPY --from=plugins /app/install.lock /app/install.lock
COPY --from=plugins /app/var/cache/opcache-preload.php /app/var/cache/opcache-preload.php
COPY --from=plugins /app/var/plugins.json /app/var/plugins.json
COPY --from=plugins /app/vendor /app/vendor
COPY --from=plugins /app/vendor-bin /app/vendor-bin


# STAGE 3


FROM stage2-root AS stage3-root
COPY stage3/usr /usr
ARG APP_ENV
COPY stage3/usr-${APP_ENV} /usr
ARG USER_ID
ARG GROUP_ID
COPY --chown=${USER_ID}:${GROUP_ID} stage3/app /app


# STAGE X


FROM base AS final
COPY --from=stage3-root / /
ENV DISABLE_EXTENSIONS="1" \
    BLUE_GREEN_DEPLOYMENT="0" \
    SHOPWARE_ES_HOSTS="" \
    SHOPWARE_ES_ENABLED="0" \
    SHOPWARE_ES_INDEXING_ENABLED="0" \
    SHOPWARE_ES_INDEX_PREFIX="" \
    SHOPWARE_HTTP_CACHE_ENABLED="1" \
    SHOPWARE_HTTP_DEFAULT_TTL="7200" \
    SHOPWARE_CDN_STRATEGY_DEFAULT="id"


FROM final AS prod


FROM final AS dev
COPY --from=node-root / /
RUN mkdir -p vendor/shopware/administration/Resources/app/administration/node_modules
COPY --from=node_modules-administration \
     /app/vendor/shopware/administration/Resources/app/administration/node_modules \
     /app/vendor/shopware/administration/Resources/app/administration/node_modules
{{#static-plugins}}
RUN mkdir -p custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules
COPY --from=node_modules-{{slug}} \
     /app/custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules \
     /app/custom/static-plugins/{{name}}/src/Resources/app/administration/node_modules
RUN mkdir -p custom/static-plugins/{{name}}/vendor
COPY --from=vendor-{{slug}} \
     /app/custom/static-plugins/{{name}}/vendor \
     /app/custom/static-plugins/{{name}}/vendor
{{/static-plugins}}
{{#composer-plugins}}
RUN mkdir -p vendor/{{package}}/src/Resources/app/administration/node_modules
COPY --from=node_modules-{{slug}} \
     /app/vendor/{{package}}/src/Resources/app/administration/node_modules \
     /app/vendor/{{package}}/src/Resources/app/administration/node_modules
{{/composer-plugins}}

FROM ${APP_ENV}
